version: '3'
services:
  docker:
    image: docker-compose
    build:
      context: ./docker/compose
      dockerfile: Dockerfile
    container_name: docker
    tty: true
    volumes:
      - ./host:/opt/work
      - /var/run/docker.sock:/var/run/docker.sock:ro
    working_dir: /opt/work
