version: '3'
services:
  docker:
    # Starts a Docker daemon at the DNS name "docker"
    # Note:
    #  * This must be called "docker" to line up with the default
    #    TLS certificate name
    #  * DOCKER_TLS_CERTDIR defaults to "/certs
    image: docker:dind-compose
    build:
      context: ./docker/dind-compose
      dockerfile: Dockerfile
    container_name: docker
    privileged: yes
    volumes:
      - ./host/certs/client:/certs/client
      - ./host/certs:/certs/
      - ./host/certs.d:/etc/docker/certs.d
      - ./host:/opt/work
    working_dir: /opt/work
    networks: 
      - net

networks: 
  net:
    driver: bridge